services:
  grafana:
    image: docker.arvancloud.ir/grafana/grafana-oss:11.5.1-ubuntu
    container_name: grafana
    ports:
      - 3030:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      # - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_METRICS_ENABLED=true
      - GF_METRICS_BASIC_AUTH_USERNAME=${GF_METRICS_BASIC_AUTH_USERNAME}
      - GF_METRICS_BASIC_AUTH_PASSWORD=${GF_METRICS_BASIC_AUTH_PASSWORD}
    networks:
      - web

networks:
  web:
    external: true

volumes:
  grafana-data:

